### ISSUE TITLE
Разработать вспомогательную функциональность для новой архитектуры подсистемы интеграций

### ISSUE THREAD

**Issue by thvvmas** [firstBitSportivnaya/PSSL#100]
По итогам архитектурного рефакторинга сделанного в рамках #85 необходимо:
1. Добавить функций подключения и установки внешних компонент из файлов;
2. Разработать процедуры записи истории интеграции для файловых обменов для вызова из пользовательских функций (при их наличии в базе);
3. Инициализации параметров подключения для разных типов интеграций (например, создание com-объекта с установленными в настройках интеграции именем com-объекта и строкой подключения);
4. Обертка для выполнения функций командной строки по данным, полученным из настроек интеграций и интеграционного потока;
5. Функции для вызова предопределенных брокеров сообщений (Rabbit Mq и Kafka);
6. Функции для упрощенной работы с файловыми обменами (например, на вход функции передавать двоичные данные и настройки интеграции, где находится каталог выгрузки, а функция выполняет запись и сохраняет данные в историю интеграции)

**Comment by ivanmolodec** [comment]
[Душнилово](https://lepekhin.ru/blog/no-functional/)

**Comment by thvvmas** [comment]
Пункты 5 и 6 вынесены в отдельные ишью: #150 и #151 соответственно

**Comment by thvvmas** [comment]
Пункты 5 и 6 вынесены в отдельные ишью: https://github.com/firstBitSportivnaya/PSSL/issues/150 и https://github.com/firstBitSportivnaya/PSSL/issues/151 соответственно
