### ISSUE TITLE
Изменить наименования общих модулей переадресации

### ISSUE THREAD

**Issue by thvvmas** [firstBitSportivnaya/PSSL#116]
Так как постфикс "Служебный" используется в модулях БСП, то необходимо служебные модули ПБП , предназначенные для переадресации вызова переименовать в "Переадресация"

**Comment by denisushakov** [comment]
@thvvmas Привет, выношу на обсуждение. Сейчас занимаюсь этой задачей.
У меня что-то идея по переадресации возникла, мы сейчас под каждый типовой ОМ, используем доп модуль переадресация, как-то жирновато, смотрю раздувается список + мне не нравится например ситуация пбп_ОбщегоНазначенияСлужебныйКлиентСервер в него еще добавить суфикс "Переадресация" кажется перебор, ну вот и подумал что если сделать отдельные модули, (пример: Переадресация, ПереадресацияКлиент, ПереадресацияКлиентСервер и т.д.) и в них уже разбить одна область, одна подсистема (как вариант) 
или это каша будет? просто хочется какой-то общий вход а из него уже перераспределять, с учетом конечно области исполнения

Ответ Ивана: "Вообще я согласен, потому что модулей реально очень много стало из-за переадресации и это перегружает систему"

**Comment by thvvmas** [comment]
"и в них уже разбить одна область, одна подсистема (как вариант) или это каша будет"

Привет, может смиксовать, чтобы каши не было? Маленькие модули объединить, как ты предлагаешь, а большие выделить в отдельные модули переадресации. Пока на примете таких три: это общего назначения служебный, общего назначения сервер и общего назначения клиент сервер.

@ivanmolodec что скажешь?

Но в этом случае доку нужно будет поправить и конкретизировать, что для таких то модулей используются отдельные модули переадресации, а все остальные перенаправляются через один общий модуль

**Comment by ivanmolodec** [comment]
Я за то чтобы этих модулей переадресации было как можно меньше. А то получается что используем мы в основном на БСП конфигурациях это, а тащим гору модулей с собой чтобы всё работало корректно

**Comment by thvvmas** [comment]
Может для ПБП пора создать группу в телеге? :)

**Comment by thvvmas** [comment]
> Я за то чтобы этих модулей переадресации было как можно меньше. А то получается что используем мы в основном на БСП конфигурациях это, а тащим гору модулей с собой чтобы всё работало корректно

В целом, идея здравая. Давайте все в один запихнем, в общем.
В идеале, конечно, чтобы избежать переиспользования БСП, при внедрении заменять бы вызов нашего модуля пбп_Переадресация на конкретный модуль.. Тогда мы и от не нужных модулей избавимся, и от лишних вызовов

**Comment by denisushakov** [comment]
@thvvmas @ivanmolodec Поддерживаю
Иван прав с точки зрения минимизации модулей, я считаю достаточно сделать под каждую область исполнения, (клиент, клиентсервер, вызовсервера и т.д.) внутри разбить на области, не думаю чтоб прям будет каша, Иван на счет количества методов уже написал выше.

Отдельную задачу надо создать или в этой могу делать?

**Comment by ivanmolodec** [comment]
> Может для ПБП пора создать группу в телеге? :)

Я за то чтобы такие вещи обсуждались тут - в ишью потом сохранится история обсуждения

**Comment by ivanmolodec** [comment]
> > Я за то чтобы этих модулей переадресации было как можно меньше. А то получается что используем мы в основном на БСП конфигурациях это, а тащим гору модулей с собой чтобы всё работало корректно
> 
> В целом, идея здравая. Давайте все в один запихнем, в общем. В идеале, конечно, чтобы избежать переиспользования БСП, при внедрении заменять бы вызов нашего модуля пбп_Переадресация на конкретный модуль.. Тогда мы и от не нужных модулей избавимся, и от лишних вызовов

Думал об этом, но пока непонятно как это реализовать. Две поставки что ли делать

**Comment by thvvmas** [comment]
> в ишью потом сохранится история обсуждения

Да неудобные тут оповещения, на личную почту приходят, а она вообще-то для квитанций и прочего жизненного)
Бота мб прикрутить, который будет обновления чата читать и пересылать по апи к конкретному ишью... Я бы подумал над этим

Лан, это флуд в данном ишью. Закрываюсь

**Comment by denisushakov** [comment]
Я что-то запутался. Ты хочешь модули переадресации по контексту разбить или вообще все методы переиспользования бсп на, условно, 5 модулей?

> > > Я за то чтобы этих модулей переадресации было как можно меньше. А то получается что используем мы в основном на БСП конфигурациях это, а тащим гору модулей с собой чтобы всё работало корректно
> > 
> > 
> > В целом, идея здравая. Давайте все в один запихнем, в общем. В идеале, конечно, чтобы избежать переиспользования БСП, при внедрении заменять бы вызов нашего модуля пбп_Переадресация на конкретный модуль.. Тогда мы и от не нужных модулей избавимся, и от лишних вызовов
> 
> Думал об этом, но пока непонятно как это реализовать. Две поставки что ли делать

так если пойти по пути под каждый контекст один модуль, то мы сведем их к минимуму, ну и не особо в глаз бросаться будет, а в дальнейшем придумать штуку автоматическую для такого изменения.

**Comment by ivanmolodec** [comment]
> > > > Я за то чтобы этих модулей переадресации было как можно меньше. А то получается что используем мы в основном на БСП конфигурациях это, а тащим гору модулей с собой чтобы всё работало корректно
> > > 
> > > 
> > > В целом, идея здравая. Давайте все в один запихнем, в общем. В идеале, конечно, чтобы избежать переиспользования БСП, при внедрении заменять бы вызов нашего модуля пбп_Переадресация на конкретный модуль.. Тогда мы и от не нужных модулей избавимся, и от лишних вызовов
> > 
> > 
> > Думал об этом, но пока непонятно как это реализовать. Две поставки что ли делать
> 
> так если пойти по пути под каждый контекст один модуль, то мы сведем их к минимуму, ну и не особо в глаз бросаться будет, а в дальнейшем придумать штуку автоматическую для такого изменения.

Давайте начнем с объединения модулей переадресации по контекстам, а потом какую-то пост-обработку добавить которая автоматически подготовит поставку для внедрения на БСП

**Comment by denisushakov** [comment]
@ivanmolodec Можно в этом ишью или новую создать?

**Comment by denisushakov** [comment]
> Я что-то запутался. Ты хочешь модули переадресации по контексту разбить или вообще все методы переиспользования бсп на, условно, 5 модулей?
> 
> > > > Я за то чтобы этих модулей переадресации было как можно меньше. А то получается что используем мы в основном на БСП конфигурациях это, а тащим гору модулей с собой чтобы всё работало корректно
> > > 
> > > 
> > > В целом, идея здравая. Давайте все в один запихнем, в общем. В идеале, конечно, чтобы избежать переиспользования БСП, при внедрении заменять бы вызов нашего модуля пбп_Переадресация на конкретный модуль.. Тогда мы и от не нужных модулей избавимся, и от лишних вызовов
> > 
> > 
> > Думал об этом, но пока непонятно как это реализовать. Две поставки что ли делать
> 
> так если пойти по пути под каждый контекст один модуль, то мы сведем их к минимуму, ну и не особо в глаз бросаться будет, а в дальнейшем придумать штуку автоматическую для такого изменения.

Вообще все на 5, а внутри уже области под каждую подсистему условно, все равно это техническая штука реализации, в нее по идее не надо лезть тому кто разрабатывает с использованием этой библиотеки

**Comment by thvvmas** [comment]
> > Я что-то запутался. Ты хочешь модули переадресации по контексту разбить или вообще все методы переиспользования бсп на, условно, 5 модулей?
> > > > > Я за то чтобы этих модулей переадресации было как можно меньше. А то получается что используем мы в основном на БСП конфигурациях это, а тащим гору модулей с собой чтобы всё работало корректно
> > > > 
> > > > 
> > > > В целом, идея здравая. Давайте все в один запихнем, в общем. В идеале, конечно, чтобы избежать переиспользования БСП, при внедрении заменять бы вызов нашего модуля пбп_Переадресация на конкретный модуль.. Тогда мы и от не нужных модулей избавимся, и от лишних вызовов
> > > 
> > > 
> > > Думал об этом, но пока непонятно как это реализовать. Две поставки что ли делать
> > 
> > 
> > так если пойти по пути под каждый контекст один модуль, то мы сведем их к минимуму, ну и не особо в глаз бросаться будет, а в дальнейшем придумать штуку автоматическую для такого изменения.
> 
> Вообще на 5, а внутри уже области под каждую подсистему условно

Я все-таки пока придерживаюсь этого варианта от Вани "Давайте начнем с объединения модулей переадресации по контекстам, а потом какую-то пост-обработку добавить которая автоматически подготовит поставку для внедрения на БСП"

**Comment by thvvmas** [comment]
Это будет путем наименьшего сопротивления, а там еще помозгуем

**Comment by denisushakov** [comment]
@thvvmas @ivanmolodec ``Вообще все на 5, а внутри уже области под каждую подсистему условно, все равно это техническая штука реализации, в нее по идее не надо лезть тому кто разрабатывает с использованием этой библиотеки``

Вроде Иван это и имел ввиду или нет?

**Comment by thvvmas** [comment]
Мы запутавсь

**Comment by ivanmolodec** [comment]
Ну сколько у нас контекстов может быть, столько и модулей
пбп_ПереадресацияСервер
...Клиент
...КлиентСервер
...ВызовСервера
Всё?

**Comment by ivanmolodec** [comment]
> @ivanmolodec Можно в этом ишью или новую создать?

В этой

**Comment by denisushakov** [comment]
> Ну сколько у нас контекстов может быть, столько и модулей пбп_ПереадресацияСервер ...Клиент ...КлиентСервер ...ВызовСервера Всё?

Да, ну + повтисп та и вроде все
