### ISSUE TITLE
Добавить объекты в подсистемы

### ISSUE THREAD

**Issue by PetrovAnton05** [firstBitSportivnaya/PSSL#139]
Новые роли не добавлены в подсистему. При обновлении определенных подсистем, роли не входят в обновление, т.к. не включены в подсистему. 
![image](https://github.com/user-attachments/assets/5bce4420-1d85-44a1-8042-ad3fe3d120f2)

**Comment by PetrovAnton05** [comment]
Аналогично с общими модулями. 
![image](https://github.com/user-attachments/assets/513d8282-f29f-4c39-add7-8236f6bcec83)

**Comment by PetrovAnton05** [comment]
Определяемый тип пбп_ПредопределенныеВсеСсылкиПереопределяемый
![image](https://github.com/user-attachments/assets/aa4e5c70-fdc1-4288-a962-6b14d39be848)

**Comment by ivanmolodec** [comment]
Спасибо, поправим
