### ISSUE TITLE
Тип определяемого типа "пбп_Пользователи"

### ISSUE THREAD

**Issue by PetrovAnton05** [firstBitSportivnaya/PSSL#142]
определяемый тип "пбп_Пользователи" - тип строка 10 - Так и должно быть или это ошибка? 
Точно не СправочникСсылка.Пользователи ? 
![image](https://github.com/user-attachments/assets/fc408dc3-f193-49cf-abbb-d39c56823cfd)

**Comment by ivanmolodec** [comment]
Да, всё верно, т.к. в конфигурации нет справочника пользователи (т.к. это в конфе-приемнике будет скорее всего БСП или какая-то своя самодельная сущность) то для её использования при накатке библиотеки нужно заполнить определяемый тип нужным справочником. Единственное - нужно наверное где-то в документации это указать о внедрении подсистемы
