### ISSUE TITLE
пбп_ИнтеграционныеПотоки: Убрать отбор Настроек с типом Файловые 

### ISSUE THREAD

**Issue by PetrovAnton05** [firstBitSportivnaya/PSSL#143]
Форма элемента справочника пбп_ИнтеграционныеПотоки.
Странный отбор, которые дает выбрать настройки только с типом ФайловыеОбмены.
Т.е. для других типов не дает выбрать настройки. 
![image](https://github.com/user-attachments/assets/003181ab-ec3c-4879-a22c-26dd262ca345)

**Comment by thvvmas** [comment]
Данный отбор является ограничением в пользовательском режиме. Для выбора настроек интеграции других типов необходимо создавать предопределенное значение с заполненным идентификатором настройки, так как по нему будет производиться поиск при дальнейших манипуляциях в коде. Это видно из условия в начале выбора настройки интеграции
```bsl
Если Не ПустаяСтрока(Объект.ИдентификаторНастройки) Тогда
    Возврат;
```
Выбрать файловые обмены можно, потому что для них предусмотрена возможность работы с помощью пользовательской функции (например, функция создания и заполнения текстового файла для последующей выгрузки в файловое хранилище)
