### ISSUE TITLE
Вызов уходит в рекурсию из пбп_Переадресация.ОбщийМодуль при наличии БСП

### ISSUE THREAD

**Issue by thvvmas** [firstBitSportivnaya/PSSL#156]
<img width="1094" alt="Снимок экрана 2024-12-03 в 23 09 31" src="https://github.com/user-attachments/assets/2857b616-8cb4-40a9-833d-0fb087c71885">

В функции ОпределитьМодульПереадресации вызов переходит в ОбщийМодуль, откуда опять в ОпределитьМодульПереадресации и т.д. Зафиксил таким образом:
<img width="788" alt="Снимок экрана 2024-12-03 в 23 36 18" src="https://github.com/user-attachments/assets/b2567710-b5eb-4fd2-b9c2-3d15f4d0a535">

И такая же проблема в СуществуетБиблиотекаСтандартныхПодсистем. Зафиксил подобным образом:
![image](https://github.com/user-attachments/assets/d07b0464-f310-4af7-a839-121e15f01e6c)

Может придумаешь решение по-элегантнее)

Смоделировать ошибку можно открыв предопределенные элементы в пользовательском или нажав на кнопку "Заполнить предопределенные" в интеграционных потоках.

**Comment by denisushakov** [comment]
@thvvmas Да, упустил момент, эту функцию общего модуля не надо переадресовывать, она должна быть автономная, т.к. она отправляет дальше, я исправлю

**Comment by denisushakov** [comment]
+
