### ISSUE TITLE
Переработать подсистемы требующие использования предопределенных значений

### ISSUE THREAD

**Issue by ivanmolodec** [firstBitSportivnaya/PSSL#16]
ПВХ Предопределенные значения и перечисления виды соответствий объектов нужно доработать чтобы их создание происходило в модулях (с возможностью подключения при обновлении), поиск по реквизиту. Это необходимо чтобы избавиться от необходимости реструктуризации базы при добавлении нового элемента/соответствия. Вынести создание этих элементов в Переопределяемый модуль чтобы избежать проблем с сравнением/объединением обновленной версии библиотеки

**Comment by KingPony282** [comment]
Создал ветку
