### ISSUE TITLE
Добавить шаблон обработки для загрузки данных из excel-файла через табличный документ

### ISSUE THREAD

**Issue by ivanmolodec** [firstBitSportivnaya/PSSL#22]

**Comment by Bayselonarrend** [comment]
Может, это вам поможет?
https://github.com/Bayselonarrend/uniloadXLS

**Comment by ivanmolodec** [comment]
> Может, это вам поможет? https://github.com/Bayselonarrend/uniloadXLS

Спасибо, очень похоже по функциональности на то что я хотел. Если вы не против, добавлю в библиотеку

**Comment by Bayselonarrend** [comment]
Да, конечно

**Comment by Bayselonarrend** [comment]
Только её бы хорошо протестировать на разных доках. Давно делал, не помню уже, точно ли все с ней в порядке

**Comment by ivanmolodec** [comment]
> Только её бы хорошо протестировать на разных доках. Давно делал, не помню уже, точно ли все с ней в порядке

Что касается документов, то к поиску нужно добавлять дату т.к. нумерация часто периодическая. Но тут нужно добавлять логику связки поля номер и дата и поиска по ним. Вообще глобально конечно какое-то переопределение поиска имеет смысл добавить, например что для такого-то справочника поиск не по коду, а по какому-то реквизиту и т.д.

**Comment by Bayselonarrend** [comment]
Доки я имел ввиду документы XLS

> Что касается документов, то к поиску нужно добавлять дату т.к. нумерация часто периодическая

Да, это правда. Трудность состоит в первую очередь в определении, какая колонка Excel даты связана с какой колонкой Excel номера. Но, так или иначе, сейчас при нахождении 2-х документов с одинаковым номером строки в полученной ТЗ задвоятся и лишнюю можно отсечь на этапе постобработки.

> например что для такого-то справочника поиск не по коду

Не встречал на практике других реквизитов, которые бы идентифицировали элемент справочника 1 к 1. Разве что какие-нибудь штрихкоды. Для таких случаев можно использовать самописный поиск под конкретную ситуацию - каждая колонка из XLS является 2-мя колонками финальной ТЗ - непосредственно колонкой с приведенным типом и колонкой со строчным значением ячейки (такие колонки с постфиксом Служебный). Вот это строчное значение можно использовать в таком случае
