### ISSUE TITLE
Доработать возврат значений выполнения метода в параметры процедур обработчиков подписок

### ISSUE THREAD

**Issue by denisushakov** [firstBitSportivnaya/PSSL#80]
Теряется связь переменных, надо прописать напрямую что данныевыбора = то что в выполнить получаем

![photo_5431826684232981120_y](https://github.com/firstBitSportivnaya/PSSL/assets/59319861/7fee6556-1a9b-4759-a552-94bbc801a802)

**Comment by ivanmolodec** [comment]
Описать это требование в документации к подсистеме
